# Generated by Django 6.0 on 2026-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_business_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='telegram_welcome',
            field=models.TextField(blank=True, default='Welcome to our store!'),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_welcome_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_welcome_uz',
            field=models.TextField(blank=True),
        ),
    ]
