# Generated by Django 6.0.3 on 2026-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for store rejection'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rejection_reason_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='rejection_reason_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('system', 'System'), ('promo', 'Promotion'), ('store_approval', 'Store Approval'), ('store_rejected', 'Store Rejected')], default='system', max_length=20),
        ),
    ]
