# Generated by Django 6.0 on 2026-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='business_description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
    ]
