# Generated by Django 4.2.29 on 2026-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_ui_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_html',
            field=models.TextField(blank=True, default='', help_text='Custom HTML template for storefront rendering'),
        ),
    ]
