# Generated by Django 4.2.29 on 2026-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_add_store_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_files',
            field=models.JSONField(blank=True, default=dict, help_text='Structured file tree for the storefront (Explorer mode)'),
        ),
    ]
