# Generated by Django 6.0.3 on 2026-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_add_store_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payment_credentials',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
