# Generated by Django 6.0.3 on 2026-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('services', 'Services'), ('restaurant', 'Restaurant'), ('bakery', 'Bakery & Sweets'), ('beauty', 'Beauty & Health'), ('home', 'Home & Garden'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
