# Generated by Django 6.0.3 on 2026-04-26 07:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        ('stores', '0010_alter_store_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum allowed debt', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('last_transaction_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debts', to='stores.store')),
            ],
            options={
                'db_table': 'erp_customer_debts',
                'ordering': ['-last_transaction_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('increase', 'Debt Increase (Credit)'), ('decrease', 'Debt Decrease (Payment)')], max_length=20)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='erp.customerdebt')),
            ],
            options={
                'db_table': 'erp_debt_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
