# Generated by Django 6.0.3 on 2026-04-19 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_batch_alter_product_slug_bundleitem_productbundle_and_more'),
        ('stores', '0009_employee_employeeshift_performancereview_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence (0-100)', max_digits=5)),
                ('reasoning', models.TextField(help_text='AI explanation for the recommendation')),
                ('factors', models.JSONField(default=dict, help_text='Factors considered by AI')),
                ('expected_sales_change', models.DecimalField(decimal_places=2, help_text='Expected % change in sales', max_digits=5)),
                ('expected_revenue_change', models.DecimalField(decimal_places=2, help_text='Expected % change in revenue', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('competitor', 'Competitor Based'), ('demand', 'Demand Based'), ('time', 'Time Based'), ('margin', 'Minimum Margin'), ('discount', 'Automatic Discount')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Category'), ('product', 'Specific Product')], default='all', max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text='Rule conditions in JSON format')),
                ('action', models.JSONField(default=dict, help_text='Action to take (e.g., set price, percentage change)')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules execute first')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='stores.store')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(choices=[('manual', 'Manual Change'), ('ai_recommendation', 'AI Recommendation'), ('pricing_rule', 'Pricing Rule Applied'), ('competitor_match', 'Competitor Price Match'), ('promotion', 'Promotion'), ('seasonal', 'Seasonal Adjustment')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stores.store')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pricingrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=200)),
                ('competitor_url', models.URLField(blank=True, help_text='URL to competitor product page')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, help_text='Our price - competitor price', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prices', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prices', to='stores.store')),
            ],
            options={
                'ordering': ['-last_checked'],
                'unique_together': {('product', 'competitor_name')},
            },
        ),
    ]
