# Generated by Django 6.0.3 on 2026-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_airecommendation_pricingrule_pricehistory_and_more'),
        ('stores', '0016_alter_store_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='products', to='stores.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., litr, kg, dona', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
