# Generated by Django 6.0 on 2026-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_tags_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_tags_uz',
            field=models.TextField(blank=True),
        ),
    ]
