# Generated by Django 6.0.3 on 2026-04-12 09:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_batch_alter_product_slug_bundleitem_productbundle_and_more'),
        ('stores', '0007_add_store_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Vendor'), ('confirmed', 'Confirmed'), ('partial', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not sent to vendor)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_purchase_orders', to='stores.store')),
            ],
            options={
                'db_table': 'erp_purchase_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ERPPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.erppurchaseorder')),
            ],
            options={
                'db_table': 'erp_purchase_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='erp.expensecategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'db_table': 'erp_expense_categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(choices=[('vendor', 'Vendor Delivery'), ('courier', 'Courier Service'), ('freight', 'Freight'), ('air', 'Air Freight'), ('sea', 'Sea Freight'), ('rail', 'Rail')], default='vendor', max_length=20)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('customs', 'At Customs'), ('arrived', 'Arrived'), ('received', 'Received'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('origin_address', models.TextField(blank=True)),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='erp.erppurchaseorder')),
            ],
            options={
                'db_table': 'erp_shipments',
                'ordering': ['-estimated_arrival'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15 days'), ('net_30', 'Net 30 days'), ('net_60', 'Net 60 days'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Vendor rating (0-10)', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='stores.store')),
            ],
            options={
                'db_table': 'erp_vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('expense_date', models.DateField(default=datetime.date.today)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('check', 'Check')], default='cash', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='erp.erppurchaseorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='stores.store')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='erp.expensecategory')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor')),
            ],
            options={
                'db_table': 'erp_expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.AddField(
            model_name='erppurchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp.vendor'),
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('transfer_date', models.DateField(default=datetime.date.today)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_incoming_transfers', to='products.warehouse')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_outgoing_transfers', to='products.warehouse')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_warehouse_transfers', to='stores.store')),
            ],
            options={
                'db_table': 'erp_warehouse_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_sent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.warehousetransfer')),
            ],
            options={
                'db_table': 'erp_warehouse_transfer_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('min_stock', 'Minimum Stock Level'), ('forecast', 'Demand Forecast'), ('seasonal', 'Seasonal Pattern')], default='min_stock', max_length=20)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_create_po', models.BooleanField(default=False, help_text='Automatically create PO when triggered')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='stores.store')),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.vendor')),
            ],
            options={
                'db_table': 'erp_stock_reorder_rules',
                'ordering': ['product__name'],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
