# Generated by Django 6.0 on 2026-02-25 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('business_type', models.CharField(choices=[('grocery', 'Grocery'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('services', 'Services'), ('restaurant', 'Restaurant'), ('beauty', 'Beauty & Health'), ('home', 'Home & Garden'), ('other', 'Other')], default='other', max_length=50)),
                ('business_description', models.TextField(blank=True)),
                ('business_model', models.CharField(choices=[('product', 'Product-based'), ('service', 'Service-based'), ('hybrid', 'Hybrid')], default='product', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pickup_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('catalog_mode', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('base_currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('RUB', 'RUB')], default='UZS', max_length=3)),
                ('use_auto_rates', models.BooleanField(default=True)),
                ('manual_exchange_rates', models.JSONField(blank=True, default=dict)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('twa_enabled', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#6366F1', max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', max_length=7)),
                ('accent_color', models.CharField(default='#F43F5E', max_length=7)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
                ('instagram_url', models.URLField(blank=True)),
                ('telegram_channel', models.CharField(blank=True, max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('contract_signed', models.BooleanField(default=False)),
                ('contract_signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('subscription_price', models.DecimalField(decimal_places=2, default=150000.0, max_digits=12)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('uz', "O'zbekcha"), ('ru', 'Русский')], default='en', max_length=5)),
                ('content', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='stores.store')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
