# Generated by Django 6.0.3 on 2026-04-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('stores', '0007_add_store_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_method', models.CharField(choices=[('fixed', 'Fixed price'), ('distance', 'Distance-based'), ('weight', 'Weight-based'), ('order_value', 'Order value-based'), ('zone', 'Zone-based')], default='fixed', max_length=20)),
                ('min_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_min_order', models.DecimalField(decimal_places=2, default=0, help_text='Free delivery for orders above this amount', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pricing_rules', to='stores.store')),
            ],
            options={
                'db_table': 'delivery_pricing',
            },
        ),
        migrations.CreateModel(
            name='DeliveryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('in_house', "O'z kuryerlarimiz"), ('yandex', 'Yandex Delivery'), ('partner', 'Hamkor xizmat'), ('pickup', 'Olib ketish')], default='in_house', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_endpoint', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('min_delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_providers', to='stores.store')),
            ],
            options={
                'db_table': 'delivery_providers',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallandi'), ('cancelled', 'Bekor qilindi')], default='planned', max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('optimized_route', models.JSONField(default=list, help_text='Ordered list of delivery coordinates')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.courier')),
            ],
            options={
                'db_table': 'delivery_routes',
                'indexes': [models.Index(fields=['courier', 'date'], name='delivery_ro_courier_13b39e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.PositiveIntegerField(default=50, help_text='Maximum orders in this slot')),
                ('current_orders', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_time_slots', to='stores.store')),
            ],
            options={
                'db_table': 'delivery_time_slots',
                'unique_together': {('store', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('zone_coordinates', models.JSONField(help_text='Array of [lat, lng] coordinates defining the zone')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='stores.store')),
            ],
            options={
                'db_table': 'delivery_zones',
                'indexes': [models.Index(fields=['store', 'is_active'], name='delivery_zo_store_i_7f935e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('address_uz', models.TextField(blank=True)),
                ('address_ru', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='18:00')),
                ('working_hours_note', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('is_24_7', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='pickup_points/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='stores.store')),
            ],
            options={
                'db_table': 'pickup_points',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='pickup_poin_latitud_bc027a_idx')],
            },
        ),
    ]
