# Generated by Django 4.2.29 on 2026-03-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seo_tags_product_seo_tags_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_store_telegram_welcome_store_telegram_welcome_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='store',
            name='eskiz_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='eskiz_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_methods',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='trial_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='store',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='base_currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR')], default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('main', 'Asosiy banner'), ('category', 'Kategoriyaga biriktirilgan')], default='main', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='banners/desktop/')),
                ('link_type', models.CharField(choices=[('none', 'Havolasiz'), ('category', 'Kategoriyaga'), ('product', 'Tovarga'), ('url', 'Tashqi havola')], default='none', max_length=20)),
                ('link_value', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='stores.store')),
            ],
            options={
                'db_table': 'store_banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='stores.store')),
            ],
            options={
                'db_table': 'staff_roles',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('staff_type', models.CharField(choices=[('employee', 'Xodim'), ('courier', 'Kuryer')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('orders_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='stores.staffrole')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='stores.store')),
            ],
            options={
                'db_table': 'branches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IKPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikpu_code', models.CharField(blank=True, max_length=100)),
                ('packaging_code', models.CharField(blank=True, max_length=100)),
                ('unit_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikpu_entries', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikpu_entries', to='stores.store')),
            ],
            options={
                'db_table': 'ikpu',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
