# Generated by Django 4.2.29 on 2026-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_balance_store_delivery_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ui_schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
